parameters:
- name: artifactName
  type: string

jobs:
  - job:
    displayName: Github Release $(parameters.artifactName)
    steps:
      - checkout: none
      - download: current
        displayName: Download artifact $(parameters.artifactName)
        artifact: $(parameters.artifactName)

      - task: GitHubRelease@1
        inputs:
          repositoryName: $(Build.Repository.Name)
          target: $(Build.SourceVersion)
          tagSource: userSpecifiedTag
          tag: $(currentVersionName)
          gitHubConnection: GitHub_ikarmus2001
          action: create
          assets: $(Pipeline.Workspace)
          isDraft: true