# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Self-hosted pool

variables:
- name: dotnetVersion
  value: '8.x'
  readonly: false
- name: nugetVersion
  value: '>=6.7.x'
- group: Android signing password

stages:
  - stage: Full_compilation
    displayName:  Compiling for all platforms
    variables: 
      CompilationConfig: Release
    jobs:
    - template: appCompilation.yml
      parameters:
        config: ${{ variables.CompilationConfig }}

