# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  pipelines:
  - pipeline: compilationPipeline
    source: YamlCompilation


pool:
  name: Self-hosted pool

stages:
  - stage: Full_compilation
    displayName:  Compiling for all platforms
    variables: 
      Environment: QA
    jobs:
    - template: appCompilation.yml
        

