stages:
  stage:
  displayName: Copy assemblies
  - ${{ if contains(parameters.framework, 'windows') }}:
    - job: 
      displayName: Copy tested assemblies - Windows
      steps:
        - checkout: none
        - task: CopyFiles@2
          inputs:
            sourceFolder: $(Build.BinariesDirectory)\$(Build.BuildNumber)_net8_0-windows10_0_19041_0
            contents: '**\AppPackages\**'
            targetFolder: $(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)_net8_0-windows10_0_19041_0

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)_net8_0-windows10_0_19041_0
            artifactName: 'Windows_${{ Parameters.Framework }}_$(Build.BuildNumber)'
            publishLocation: pipeline

  - ${{ if contains(parameters.framework, 'android') }}:
    - job: 
      displayName: Copy tested assemblies - Android
      steps:
        - checkout: none
        - task: CopyFiles@2
          inputs:
            sourceFolder: $(Build.BinariesDirectory)\$(Build.BuildNumber)_net8_0-android34
            contents: '**\publish\*-Signed.apk'
            targetFolder: $(Build.ArtifactStagingDirectory)\$(Build.BuildNumber)_net8_0-android34

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)_net8_0-android34
            artifactName: 'Android_${{ Parameters.Framework }}_$(Build.BuildNumber)'
            publishLocation: pipeline