trigger:
- main

pool:
  name: Self-hosted pool

steps:
- script: |
    %%latex%%\latexmk.exe $env:BUILD_SOURCESDIRECTORY/Praca_inzynierska/main.tex
  displayName: Running latexmk

- script: |
    %%latex%%\pdflatex.tex $env:BUILD_SOURCESDIRECTORY/Praca_inzynierska/main.tex
  displayName: 'Export to PDF'

- publish: /Praca_inzynierska/main.pdf
  artifact: PracaInzynierska_$(Build.BuildNumber).pdf