# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Self-hosted pool

variables:
- name: dotnetSdkVersion
  value: '8.x'
  readonly: false
- name: nugetVersion
  value: '>=6.7.x'
- group: Android signing password
- name: WindowsArtifactName
  value: ''
- name: AndroidArtifactName
  value: ''

stages:
  - template: templates/envPreparationStage.yml
    parameters:
      dotnetVersion: $(dotnetSdkVersion)

  - stage: Quick_debug
    jobs:
      - job: EmptyVars
        steps:
          - checkout: none
          - pwsh: Write-Host $(WindowsArtifactName)
            displayName: logging $(WindowsArtifactName)
          - pwsh: Write-Host $(WindowsArtifactName)
            displayName: logging $(AndroidArtifactName)
      - job:
        displayName: Assignment
        steps:
          - checkout: none
          - pwsh: Write-Host "##vso[task.setvariable variable=WindowsArtifactName;isOutput=true]whatevertestingWin"
            displayName: Export artifact name to pipeline
          - pwsh: Write-Host "##vso[task.setvariable variable=AndroidArtifactName;isOutput=true]whatevertestingAndroid"
            displayName: Export artifact name to pipeline
      - job: filled
        steps:
          - checkout: none
          - pwsh: Write-Host $(WindowsArtifactName)
            displayName: logging $(WindowsArtifactName)
          - pwsh: Write-Host $(WindowsArtifactName)
            displayName: logging $(AndroidArtifactName)

  - template: templates/appCompilation.yml
    parameters:
      config: Release
      framework: net8.0-windows10.0.19041.0
      outputArtifactName: WindowsArtifactName
      dotnetVersion: $(dotnetSdkVersion)

  - stage: Testing
    jobs:
      - template: templates/unitTestStage.yml
        parameters:
          dotnetVersion: $(dotnetSdkVersion)

  - template: templates/appCompilation.yml
    parameters:
      config: Release
      framework: net8.0-android34
      outputArtifactName: AndroidArtifactName
      dotnetVersion: $(dotnetSdkVersion)

  - stage: FurtherDebug
    jobs:
      - job:
        steps:
          - pwsh: Write-Host $(WindowsArtifactName)
            displayName: logging $(WindowsArtifactName)
          - pwsh: Write-Host $(WindowsArtifactName)
            displayName: logging $(AndroidArtifactName)

  - stage: Deployment
    jobs:  
      - template: templates/GithubReleaseJob.yml
        parameters:
          artifactName: $[WindowsArtifactName]

      - template: templates/GithubReleaseJob.yml
        parameters:
          artifactName: $[AndroidArtifactName]
