# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Self-hosted pool

variables:
- name: dotnetSdkVersion
  value: '8.x'
  readonly: false
- name: nugetVersion
  value: '>=6.7.x'
- group: Android signing password
- name: WindowsArtifactName
  value: ''
- name: AndroidArtifactName
  value: ''

stages:
  - template: CI/envPreparationStage.yml
    parameters:
      dotnetVersion: $(dotnetSdkVersion)

  - stage: Quick_debug
    jobs:
      - job: EmptyVars
        steps:
          - script: echo $[WindowsArtifactName]
            displayName: logging $[WindowsArtifactName]
          - script: echo $[WindowsArtifactName]
            displayName: logging $[AndroidArtifactName]
      - job:
        displayName: Assignment
        steps:
          - script: echo "##vso[task.setvariable variable=WindowsArtifactName]whatevertestingWin"
            displayName: Export artifact name to pipeline
          - script: echo "##vso[task.setvariable variable=AndroidArtifactName]whatevertestingAndroid"
            displayName: Export artifact name to pipeline
      - job: filled
        steps:
          - script: echo $[WindowsArtifactName]
            displayName: logging $[WindowsArtifactName]
          - script: echo $[WindowsArtifactName]
            displayName: logging $[AndroidArtifactName]

  - template: CI/appCompilation.yml
    parameters:
      config: Release
      framework: net8.0-windows10.0.19041.0
      outputArtifactName: WindowsArtifactName
      dotnetVersion: $(dotnetSdkVersion)

  - stage: Testing
    jobs:
      - template: CI/unitTestStage.yml
        parameters:
          dotnetVersion: $(dotnetSdkVersion)

  - template: appCompilation.yml
    parameters:
      config: Release
      framework: net8.0-android34
      outputArtifactName: AndroidArtifactName
      dotnetVersion: $(dotnetSdkVersion)

  - stage: FurtherDebug
    jobs:
      - job:
        steps:
          - pwsh: echo $[WindowsArtifactName]
            displayName: logging $[WindowsArtifactName]
          - pwsh: echo $[WindowsArtifactName]
            displayName: logging $[AndroidArtifactName]

  - stage: Deployment
    jobs:  
      - template: CI/GithubReleaseJob.yml
        parameters:
          artifactName: $[WindowsArtifactName]

      - template: CI/GithubReleaseJob.yml
        parameters:
          artifactName: $[AndroidArtifactName]
